import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavMenu } from "@/components/layout/navbar";
import FooterSection from "@/components/layout/footer";
import "./globals.css";
import { AuthProvider } from "@/lib/context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-[#f4f3fc]`}
      >
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <NavMenu />
            <main className="flex-1 container mx-auto p-8 pt-24">
              {children}
            </main>
            <FooterSection />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
