import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "src/app/components/navbar";
import { NavMenu } from "src/app/components/navbar";
import FooterSection from "@/components/footer"
import "src/app/styles/globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen flex flex-col`}
      >
        {/* Navbar*/}
        <NavMenu />

        {/* Main content */}
        <main className="flex-1 w-full">{children}</main>

        {/* Footer */}
        <FooterSection />
      </body>
    </html>
  );
}
